### ISSUE TITLE
Total initial infections calculation is incorrect

### ISSUE THREAD

**Issue by joshuaschwab** [pennsignals/chime#50]
Change #17 Hid Prop_of_Det and calculated Total Infection as below
Total Infections = Current_Num_Hospitilizaed / Market share / Hospitilization Rate

But I think this is incorrect in an important way. Hospitalization rate is the percent of infected people who **eventually** go to the hospital. But there are currently lots of people who just got infected and are not sick yet. Current_num_hospitalized is a function of the number of infections over the last ~14 days. 

I suggest unhiding Prop_of_Det.

**Comment by joshuaschwab** [comment]
I also suggest changing the text from:
The 53 confirmed cases in the region imply a 20% rate of detection. This is based on current inputs for Hospitalizations (2), Hospitalization rate (5%), Region size (4119405), and Hospital market share (15%)
to
The [detection rate] rate of detection and [confirmed cases] confirmed cases imply a total number of cases of [total infections].

**Comment by mdbecker** [comment]
Thanks @joshuaschwab we pushed out a change late last night to address exactly this issue of making the parameters to the model clearer. Is your concern is that `current_num_hospitalized` is a lagging indicator and therefore not necessarily an accurate estimate? 

On [line 170](https://github.com/pennsignals/chime/blob/master/app.py#L170) we estimate the initial infected for the SIR model as `initial_infections / detection_prob`. `detection_prob` is calculated on [line 59](https://github.com/pennsignals/chime/blob/master/app.py#L59) as `initial_infections / total_infections` and `total_infections` is calculated as you mentioned in your OP.

Is there a better way to estimate the initial value of `I` for the model given the information we have available to us? We know the number of reported suspected cases and we know the number of patients in our hospitals. How would you suggest we improve this. Thanks!

**Comment by joshuaschwab** [comment]
Yes, my concern is that current_num_hospitalized is a lagging indicator. It is a significant underestimate when the virus is spreading rapidly.

There are ways to better estimate `I`. One possibility is to use the SIR model to simulate infections over the **previous** two weeks. But this is going to be a bit complicated and would require some different input parameters.

For now I suggest unhiding Prop_of_Det (reverting #17) because it's quick and the simulations will be valid. Users are using this tool to make key decisions by the hour so I think it's important to make a quick but correct fix.

**Comment by mdbecker** [comment]
@joshuaschwab thanks for this! We've unhidden `Prop_of_Det` in the latest version. It's in the second paragraph of the main page "The estimated number of currently infected individuals is 533. The 53 confirmed cases in the region imply a **10% rate** of detection. This is based on current inputs for Hospitalizations (4), Hospitalization rate (5%), Region size (4119405), and Hospital market share (15%)."

**Comment by joshuaschwab** [comment]
Thank you but I'm sorry the simulations are still incorrect. 
Sorry I was unclear - the proposed fix is to bring back the `Prop_of_Det` slider. 
[If anyone is looking here, check the slack channel for current discussion]

**Comment by joshuaschwab** [comment]
Users are using this tool to make key decisions by the hour so I think it's important to make a quick but correct fix.
There's nothing wrong with having a Prop_of_Det slider. When Prop_of_Det is a parameter the total initial infections is correct and all projects are correct (given the parameters) and the source of uncertainty (that we don't know how many people are detected) is transparent to the user.
Whereas the current calculation of total initial infections is definitely not correct (it's always too low).

In the next day or two we can work on different ways of estimating total initial infections, such as running the simulation for the previous two weeks, but it's going to take some careful thought.
